import "./globals.css";
import Providers from "../Components/providers";
import AppBar from "../Components/AppBar"

export const metadata = {
  title: "Algerie Telecom",
  description: "Generated by Norhane Cherif",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body>
        
        <Providers>
        <AppBar/>
        {children}               
        </Providers>
      </body>
    </html>
  );
}