import "./globals.css";
import Providers from "../Components/providers";
import AppBar from "../Components/AppBar"
import {styles} from "../styles"

export const metadata = {
  title: "Algerie Telecom",
  description: "Generated by Norhane Cherif",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body>
        <Providers>
          {children}     
        </Providers>
      </body>
    </html>
  );
}